[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.25"

[features]
resolution = true
skip-lint = false

[programs.devnet]
chainsta = "BQV6kT5JULTSypCohqw8H8ERfL74SkexGFCK44o5Szi2"

[programs.localnet]
chainsta = "BQV6kT5JULTSypCohqw8H8ERfL74SkexGFCK44o5Szi2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
